from __future__ import annotations

import json
from pathlib import Path

import pytest

from src.skill_builder.builder import build_skill_library
from src.skill_builder.models import ModuleInfo, SkillCandidate, VerificationResult, VerificationStageResult
from src.skill_builder.spec_generator import generate_skill_spec
from src.skill_builder.frontend import parse_project
from src.skill_builder.hierarchy import (
    build_module_hierarchy,
    build_skill_candidates,
    compute_dependency_closure,
    mermaid_dependency_graph,
    module_dependency_graph,
)
from src.skill_builder.parser import parse_modules
from src.skill_builder.schema import validate_module_info


class FakeClassifierLLM:
    def __init__(self) -> None:
        self.calls = 0

    def complete_structured(self, messages: list[dict[str, str]], schema, *, temperature: float = 0.0):
        self.calls += 1
        if "claims" in schema.model_fields:
            context = json.loads(messages[-1]["content"])
            evidence_ids = [item["id"] for item in context["available_evidence"]]
            port_ids = [item["id"] for item in context["available_evidence"] if item["id"].startswith("E_PORT")]
            comment_ids = [item["id"] for item in context["available_evidence"] if item["id"].startswith("E_COMMENT")]
            payload = {
                "claims": [
                    {
                        "id": "C_FUNC_LLM_001",
                        "kind": "function",
                        "claim": "The skill behavior is inferred from the module interface and available source comments.",
                        "status": "inferred",
                        "confidence": 0.72,
                        "evidence_ids": (comment_ids + port_ids)[:8] or evidence_ids[:1],
                        "conditions": ["Generated by fake evidence-aware spec LLM for tests."],
                    },
                    {
                        "id": "C_UNKNOWN_LLM_001",
                        "kind": "timing",
                        "claim": "Exact latency is not established by the available evidence.",
                        "status": "unknown",
                        "confidence": 0.0,
                        "evidence_ids": [],
                        "conditions": ["No source test, assertion, or formal result proves precise latency."],
                    },
                ],
                "unknowns": ["Exact latency is unverified."],
                "retrieval_text": "evidence linked rtl skill",
            }
            return schema.model_validate(payload)

        prompt = messages[-1]["content"].lower()
        if "fifo" in prompt:
            payload = {
                "category": "buffering",
                "interfaces": ["fifo"],
                "patterns": ["fifo"],
                "keywords": ["fifo", "buffering"],
            }
        elif "round_robin" in prompt or "arbiter" in prompt:
            payload = {
                "category": "control",
                "interfaces": ["arbiter"],
                "patterns": ["arbiter"],
                "keywords": ["arbiter", "control"],
            }
        elif "reset" in prompt or "sync" in prompt:
            payload = {
                "category": "cdc",
                "interfaces": ["cdc"],
                "patterns": ["synchronizer"],
                "keywords": ["synchronizer", "cdc"],
            }
        else:
            payload = {
                "category": "control",
                "interfaces": ["rtl"],
                "patterns": ["counter"],
                "keywords": ["counter", "control"],
            }
        payload.update(
            {
                "functional_summary": "This module provides a deterministic RTL building block inferred from its interface.",
                "structural_summary": "The module structure is summarized from extracted ports, parameters, and instance edges.",
                "behavior_summary": "The observable behavior summary is inferred from source comments and interface signals.",
                "integration_notes": ["Check clock, reset, and handshake timing before integration."],
                "limitations": ["Do not treat the generated template as functionally equivalent to source RTL."],
                "use_cases": ["Use when the extracted interface and behavior summary match the target design."],
            }
        )
        return schema.model_validate(payload)

    def complete_text(self, messages: list[dict[str, str]], *, temperature: float = 0.0) -> str:
        raise AssertionError("skill builder should request structured JSON, not text")


class BadEvidenceSpecLLM:
    def complete_structured(self, messages: list[dict[str, str]], schema, *, temperature: float = 0.0):
        payload = {
            "claims": [
                {
                    "id": "C_BAD_001",
                    "kind": "function",
                    "claim": "This claim points at missing evidence.",
                    "status": "inferred",
                    "confidence": 0.5,
                    "evidence_ids": ["E_MISSING_001"],
                    "conditions": [],
                }
            ],
            "unknowns": [],
            "retrieval_text": "bad",
        }
        return schema.model_validate(payload)

    def complete_text(self, messages: list[dict[str, str]], *, temperature: float = 0.0) -> str:
        raise AssertionError("skill spec generator should request structured JSON, not text")


def write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def test_parse_simple_ansi_module(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "ansi.v",
        """
module simple_ansi (
    input wire clk,
    input wire rst,
    input wire [7:0] data_i,
    output reg valid_o
);
endmodule
""",
    )
    modules = parse_modules(rtl)
    assert [module.name for module in modules] == ["simple_ansi"]
    assert [port.name for port in modules[0].ports] == ["clk", "rst", "data_i", "valid_o"]
    assert modules[0].ports[2].width == "[7:0]"
    assert modules[0].ports[3].direction == "output"


def test_parse_non_ansi_module(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "non_ansi.v",
        """
module non_ansi(clk, rst_n, data_o);
input clk;
input rst_n;
output [3:0] data_o;
endmodule
""",
    )
    module = parse_modules(rtl)[0]
    ports = {port.name: port for port in module.ports}
    assert ports["clk"].direction == "input"
    assert ports["rst_n"].direction == "input"
    assert ports["data_o"].direction == "output"
    assert ports["data_o"].width == "[3:0]"


def test_parse_parameterized_module(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "param.v",
        """
module param_mod #(
    parameter WIDTH = 16,
    parameter DEPTH = 4
) (
    input wire [WIDTH-1:0] data_i,
    output wire [DEPTH-1:0] data_o
);
endmodule
""",
    )
    module = parse_modules(rtl)[0]
    assert [(param.name, param.default) for param in module.parameters] == [
        ("WIDTH", "16"),
        ("DEPTH", "4"),
    ]
    assert module.ports[0].width == "[WIDTH-1:0]"


def test_parse_module_with_comments(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "comments.v",
        """
// Top comment for extraction.
/*
 * Block comment survives as readable text.
 */
module commented(input wire clk);
endmodule
""",
    )
    module = parse_modules(rtl)[0]
    assert any("Top comment" in comment for comment in module.comments)
    assert any("Block comment" in comment for comment in module.comments)


def test_parse_module_with_no_parameters(tmp_path: Path) -> None:
    rtl = write(tmp_path / "noparam.v", "module noparam(input wire clk); endmodule\n")
    module = parse_modules(rtl)[0]
    assert module.name == "noparam"
    assert module.parameters == []


def test_parse_multiple_modules_in_one_file(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "multi.v",
        """
module first(input wire clk); endmodule
module second(input wire clk, output wire done); endmodule
""",
    )
    assert [module.name for module in parse_modules(rtl)] == ["first", "second"]


def test_frontend_extracts_module_ir_instances_and_hierarchy(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "top.sv",
        """
module child(input logic clk);
endmodule

module top(input logic clk);
    child u_child (.clk(clk));
    external_ip u_ip (.clk(clk));
endmodule

module island(input logic clk);
endmodule
""",
    )
    modules = parse_project([rtl])
    by_name = {module.name: module for module in modules}
    assert set(by_name) == {"child", "top", "island"}
    assert by_name["top"].parse_backend in {"pyslang", "regex"}
    assert by_name["top"].instances[0].module_name == "child"
    assert by_name["top"].instances[0].port_connections == {"clk": "clk"}

    hierarchy = build_module_hierarchy(modules)
    assert hierarchy.edges["top"] == {"child"}
    assert hierarchy.roots == ["island", "top"]
    assert hierarchy.unresolved_dependencies == {"top": {"external_ip"}}


def test_pyslang_instance_extractor_ignores_procedural_constructs(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "ast_instances.sv",
        """
module child(input logic clk); endmodule
module top(input logic clk);
    for (genvar i = 0; i < 4; i++) begin : g
        child u_child(.clk(clk));
    end
    function automatic logic bin2gray(input logic value);
        return value ^ (value >> 1);
    endfunction
    initial begin
        $display("test");
        $error("error");
    end
endmodule
""",
    )
    modules = parse_project([rtl])
    top = {module.name: module for module in modules}["top"]
    assert top.instance_backend == "pyslang_ast"
    assert [(inst.module_name, inst.instance_name) for inst in top.instances] == [("child", "u_child")]
    hierarchy = build_module_hierarchy(modules)
    assert hierarchy.unresolved_dependencies == {}


def test_pyslang_instance_extractor_handles_parameterized_instance(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "param_inst.sv",
        """
module axis_fifo #(parameter DEPTH = 4) (input logic clk); endmodule
module top(input logic clk);
    axis_fifo #(
        .DEPTH(16)
    ) u_fifo (
        .clk(clk)
    );
endmodule
""",
    )
    top = {module.name: module for module in parse_project([rtl])}["top"]
    assert len(top.instances) == 1
    inst = top.instances[0]
    assert inst.module_name == "axis_fifo"
    assert inst.instance_name == "u_fifo"
    assert inst.parameter_overrides == {"DEPTH": "16"}
    assert inst.port_connections == {"clk": "clk"}
    assert inst.source is not None
    assert inst.source.line_start is not None


def test_frontend_extracts_structural_facts_for_evidence_pack(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "facts.sv",
        """
module facts(input logic clk, input logic rst, output logic full);
    logic [7:0] mem [0:3];
    logic [2:0] count;

    assign full = count == 4;

    always_ff @(posedge clk) begin
        if (rst) begin
            count <= 0;
        end
    end

    assert property (count <= 4);
endmodule
""",
    )
    module = parse_project([rtl])[0]
    assert [fact.name for fact in module.memory_candidates] == ["mem"]
    assert module.always_blocks
    assert module.always_blocks[0].expression == "posedge clk"
    assert [fact.name for fact in module.continuous_assignments] == ["full"]
    assert module.assertions[0].kind == "assert_statement"
    assert module.assertions[0].expression == "count <= 4"


def test_hierarchy_keeps_self_recursive_module_as_root(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "self_ref.v",
        """
module self_ref(input wire clk);
    self_ref u_self (.clk(clk));
endmodule
""",
    )
    hierarchy = build_module_hierarchy(parse_project([rtl]))
    assert hierarchy.edges["self_ref"] == {"self_ref"}
    assert hierarchy.roots == ["self_ref"]


def test_skill_candidate_standalone_closure(tmp_path: Path) -> None:
    rtl = write(tmp_path / "one.v", "module one(input wire clk); endmodule\n")
    candidate = compute_dependency_closure("one", build_module_hierarchy(parse_project([rtl])))
    assert candidate.candidate_kind == "standalone"
    assert candidate.dependency_modules == []
    assert candidate.is_self_contained is True


def test_skill_candidate_single_and_multilevel_dependencies(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "deps.v",
        """
module leaf(input wire clk); endmodule
module middle(input wire clk); leaf u_leaf(.clk(clk)); endmodule
module top(input wire clk); middle u_middle(.clk(clk)); endmodule
""",
    )
    candidate = compute_dependency_closure("top", build_module_hierarchy(parse_project([rtl])))
    assert candidate.candidate_kind == "composite"
    assert candidate.dependency_modules == ["middle", "leaf"]
    assert len(candidate.source_files) == 1
    graph = module_dependency_graph(build_module_hierarchy(parse_project([rtl])))
    assert graph["direct_edges"]["top"] == ["middle"]
    assert graph["direct_edges"]["middle"] == ["leaf"]
    assert graph["closure_edges"]["top"] == ["middle", "leaf"]
    mermaid = mermaid_dependency_graph(build_module_hierarchy(parse_project([rtl])), closure=True)
    assert "m_top --> m_middle" in mermaid
    assert "m_top --> m_leaf" in mermaid


def test_skill_candidate_shared_dependency_is_deduped(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "shared.v",
        """
module common(input wire clk); endmodule
module a(input wire clk); common u_common(.clk(clk)); endmodule
module b(input wire clk); common u_common(.clk(clk)); endmodule
module top(input wire clk); a u_a(.clk(clk)); b u_b(.clk(clk)); endmodule
""",
    )
    candidate = compute_dependency_closure("top", build_module_hierarchy(parse_project([rtl])))
    assert candidate.dependency_modules.count("common") == 1
    assert candidate.dependency_modules == ["a", "common", "b"]


def test_skill_candidate_cycle_is_reported(tmp_path: Path) -> None:
    rtl = write(
        tmp_path / "cycle.v",
        """
module a(input wire clk); b u_b(.clk(clk)); endmodule
module b(input wire clk); a u_a(.clk(clk)); endmodule
""",
    )
    candidate = compute_dependency_closure("a", build_module_hierarchy(parse_project([rtl])))
    assert candidate.candidate_kind == "cyclic"
    assert candidate.hierarchy_warnings


def test_skill_candidate_external_dependency_is_unresolved(tmp_path: Path) -> None:
    rtl = write(tmp_path / "missing.v", "module top(input wire clk); missing_ip u_ip(.clk(clk)); endmodule\n")
    candidate = compute_dependency_closure("top", build_module_hierarchy(parse_project([rtl])))
    assert candidate.unresolved_dependencies == ["missing_ip"]
    assert candidate.is_self_contained is False
    assert candidate.candidate_kind == "unresolved"


def test_vendor_primitive_dependency_is_classified(tmp_path: Path) -> None:
    rtl = write(tmp_path / "vendor.v", "module top(input wire clk); RAMB36E1 u_ram(); endmodule\n")
    candidate = compute_dependency_closure("top", build_module_hierarchy(parse_project([rtl])))
    assert candidate.vendor_primitives == ["RAMB36E1"]
    assert candidate.unresolved_dependencies == []


def test_builder_reports_generated_tb_compile_failure_separately(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(
        repo / "rtl" / "tb_fail.v",
        """
module tb_fail(input wire clk, input wire [WIDTH-1:0] data);
localparam WIDTH = 8;
endmodule
""",
    )
    report = build_skill_library(repo, tmp_path / "skills", clean=True, llm=FakeClassifierLLM())
    skill = report["skills"][0]
    assert skill["verification"]["source_compile"] == "passed"
    assert skill["verification"]["generated_tb_compile"] == "failed"
    assert skill["verification"]["failure_stage"] == "generated_tb_compile"
    gates = {gate["name"]: gate for gate in skill["quality_gates"]}
    assert gates["source_compile"]["status"] == "passed"
    assert gates["generated_tb_compile"]["status"] == "failed"
    assert gates["generated_tb_compile"]["evidence_path"] == "tool_runs/tb_compile.json"


def test_builder_reports_dependency_closure_incomplete(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "rtl" / "top.v", "module top(input wire clk); child u_child(.clk(clk)); endmodule\n")
    report = build_skill_library(repo, tmp_path / "skills", clean=True, llm=FakeClassifierLLM())
    skill = report["skills"][0]
    assert skill["unresolved_dependencies"] == ["child"]
    assert skill["verification"]["failure_category"] == "dependency_closure_incomplete"
    gates = {gate["name"]: gate for gate in skill["quality_gates"]}
    assert gates["dependency_closure"]["status"] == "failed"
    assert gates["dependency_closure"]["blocking_for_quality"] is True
    assert report["quality_gate_counts"]["dependency_closure"]["failed"] == 1


def test_skill_spec_rejects_unknown_evidence_ids() -> None:
    module = ModuleInfo(name="demo", source_path=Path("demo.v"), functional_summary="demo summary")
    candidate = SkillCandidate(skill_id="demo", root_module="demo", root_source="demo.v")
    passed = VerificationStageResult(status="passed")
    verification = VerificationResult(passed, passed, passed)
    evidence_pack = {
        "evidence": [
            {
                "id": "E_PORT_001",
                "type": "port",
                "status": "observed",
                "name": "clk",
            }
        ]
    }
    with pytest.raises(ValueError, match="unknown evidence ids"):
        generate_skill_spec(
            module,
            candidate,
            evidence_pack,
            verification,
            "silver",
            BadEvidenceSpecLLM(),
        )


def test_duplicate_module_definitions_are_reported(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "rtl" / "a.v", "module dup(input wire clk); endmodule\n")
    write(repo / "alt" / "a.v", "module dup(input wire clk); endmodule\n")
    report = build_skill_library(repo, tmp_path / "skills", clean=True, llm=FakeClassifierLLM())
    assert "dup" in report["dependencies"]["duplicate_modules"]
    assert all(skill["candidate_kind"] == "unresolved" for skill in report["skills"])
    assert all(skill["quality_tier"] == "rejected" for skill in report["skills"])
    assert all(skill["verification"]["failure_category"] == "duplicate_module_definition" for skill in report["skills"])


def test_malformed_file_does_not_crash_builder(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "rtl" / "broken.v", "module broken(input wire clk\n")
    report = build_skill_library(repo, tmp_path / "skills", clean=True, llm=FakeClassifierLLM())
    assert report["rtl_files_scanned"] == 1
    assert report["modules_extracted"] == 0
    assert report["skills_generated"] == 0
    assert (tmp_path / "skills" / "report.json").exists()


def test_module_info_schema_reports_missing_required_fields() -> None:
    errors = validate_module_info({"name": "bad"})
    assert errors
    assert any("missing top-level fields" in error for error in errors)


def test_sample_repo_golden_output(tmp_path: Path) -> None:
    repo = Path("work/sample_rtl_repo")
    output = tmp_path / "skills"
    report = build_skill_library(repo, output, clean=True, llm=FakeClassifierLLM())

    assert report["skills_generated"] == 4
    assert sum(report["frontend"]["backend_counts"].values()) == 4
    assert report["frontend"]["module_count"] == 4
    assert sorted(report["frontend"]["root_modules"]) == [
        "pulse_counter",
        "reset_sync",
        "round_robin",
        "simple_fifo",
    ]
    assert report["frontend"]["unresolved_dependencies"] == {}
    assert report["frontend"]["parse_warnings"]
    assert (output / "dependency_graph.mmd").exists()
    assert (output / "dependency_closure_graph.mmd").exists()
    assert report["dependency_graph"]["direct_edges"]["simple_fifo"] == []
    assert report["dependency_graph"]["closure_edges"]["simple_fifo"] == []
    assert report["dependency_graph"]["mermaid_closure"].endswith("dependency_closure_graph.mmd")
    assert (output / "report.json").exists()
    assert all(skill["sim_ok"] for skill in report["skills"])
    assert report["quality_gate_counts"]["metadata_schema"]["passed"] == 4
    assert report["quality_gate_counts"]["dependency_closure"]["passed"] == 4
    assert report["quality_gate_counts"]["source_compile"]["passed"] == 4
    assert report["quality_gate_counts"]["generated_tb_compile"]["passed"] == 4
    assert report["quality_gate_counts"]["smoke_simulation"]["passed"] == 4
    assert report["quality_gate_counts"]["original_tests"]["absent"] == 4

    for skill in report["skills"]:
        skill_dir = output / skill["skill_name"]
        module_name = skill["name"]
        assert (skill_dir / "module_info.json").exists()
        assert (skill_dir / "README.md").exists()
        assert (skill_dir / "template.v").exists()
        assert (skill_dir / "module_ir.json").exists()
        assert (skill_dir / "closure.json").exists()
        assert (skill_dir / "evidence.json").exists()
        assert (skill_dir / "skill_spec.json").exists()
        assert (skill_dir / "provenance.json").exists()
        assert (skill_dir / "adaptation.json").exists()
        assert (skill_dir / "tool_runs" / "frontend.json").exists()
        assert (skill_dir / "tool_runs" / "source_compile.json").exists()
        assert (skill_dir / "tool_runs" / "tb_compile.json").exists()
        assert (skill_dir / "tool_runs" / "simulation.json").exists()
        assert (skill_dir / "examples" / "instantiation.v").exists()
        assert (skill_dir / "examples" / f"tb_{module_name}.v").exists()
        assert (skill_dir / "tests" / "generated" / "generated_smoke_tb.v").exists()
        assert (skill_dir / "tests" / "original" / "README.md").exists()

        module_info = json.loads((skill_dir / "module_info.json").read_text(encoding="utf-8"))
        assert module_info["provenance"]["source_file"]
        assert module_info["provenance"]["detected_module_name"] == module_name
        assert module_info["provenance"]["builder_version"]
        assert module_info["provenance"]["parser_mode"] == "deterministic"
        assert validate_module_info(module_info) == []

        module_ir = json.loads((skill_dir / "module_ir.json").read_text(encoding="utf-8"))
        assert module_ir["name"] == module_name
        assert module_ir["ports"]

        manifest = json.loads((skill_dir / "manifest.json").read_text(encoding="utf-8"))
        assert manifest["closure_manifest"] == "closure.json"
        assert manifest["generated_smoke_test"] == "tests/generated/generated_smoke_tb.v"
        assert manifest["original_tests"] == []

        closure = json.loads((skill_dir / "closure.json").read_text(encoding="utf-8"))
        assert closure["root_module"] == module_name
        assert closure["root_source"].startswith("rtl/")
        assert closure["dependency_completeness"] in {"complete", "incomplete"}
        assert all(path.startswith("rtl/") for path in closure["rtl_files"]["packaged"])
        assert all(not Path(path).is_absolute() for path in closure["rtl_files"]["original_to_packaged"])
        assert closure["verification_boundary"]["source_compile"] in {
            "passed",
            "failed",
            "timeout",
            "tool_missing",
        }
        assert closure["verification_boundary"]["original_tests"] == "absent"

        quality = json.loads((skill_dir / "quality.json").read_text(encoding="utf-8"))
        assert quality["verification"]["original_tests"]["status"] == "absent"
        assert quality["verification"]["formal_verification"]["status"] == "absent"
        assert quality["verification"]["manual_review"]["status"] == "absent"
        quality_gates = {gate["name"]: gate for gate in quality["quality_gates"]["gates"]}
        assert quality_gates["metadata_schema"]["status"] == "passed"
        assert quality_gates["dependency_closure"]["status"] == "passed"
        assert quality_gates["source_compile"]["evidence_path"] == "tool_runs/source_compile.json"
        assert quality_gates["original_tests"]["status"] == "absent"
        assert quality["quality_gates"]["summary"]["passed"] >= 5

        evidence = json.loads((skill_dir / "evidence.json").read_text(encoding="utf-8"))
        assert evidence["module"] == module_name
        assert evidence["source_compile"] in {"passed", "failed", "timeout", "tool_missing"}
        assert evidence["evidence"]
        assert all(item["id"].startswith("E_") for item in evidence["evidence"])
        assert {port["type"] for port in evidence["ports"]} == {"port"}
        if module_name == "simple_fifo":
            assert [item["name"] for item in evidence["memory_candidates"]] == ["mem"]
            assert evidence["always_blocks"]
            assert {item["name"] for item in evidence["continuous_assignments"]} == {"full", "empty"}
            assert any(item["id"].startswith("E_MEM") for item in evidence["evidence"])
            assert any(item["id"].startswith("E_ALWAYS") for item in evidence["evidence"])
            assert any(item["id"].startswith("E_ASSIGN") for item in evidence["evidence"])
        assert {stage["stage"] for stage in evidence["verification_stages"]} == {
            "source_compile",
            "generated_tb_compile",
            "smoke_simulation",
        }
        evidence_id_set = {item["id"] for item in evidence["evidence"]}

        skill_spec = json.loads((skill_dir / "skill_spec.json").read_text(encoding="utf-8"))
        assert skill_spec["root_module"] == module_name
        assert skill_spec["retrieval_text"]
        assert skill_spec["unknowns"]
        assert any("Functional equivalence" in item for item in skill_spec["unknowns"])
        assert {claim["status"] for claim in skill_spec["claims"]} <= {
            "observed",
            "inferred",
            "validated",
            "unknown",
            "conflicted",
        }
        assert any(claim["kind"] == "function" for claim in skill_spec["claims"])
        verification_claims = [claim for claim in skill_spec["claims"] if claim["kind"] == "verification"]
        assert verification_claims
        assert verification_claims[0]["evidence_ids"]
        for spec_claim in skill_spec["claims"]:
            assert "claim" in spec_claim
            assert "evidence_ids" in spec_claim
            assert set(spec_claim["evidence_ids"]) <= evidence_id_set

        provenance = json.loads((skill_dir / "provenance.json").read_text(encoding="utf-8"))
        assert provenance["root_module"] == module_name
        assert provenance["source_hashes"]

        adaptation = json.loads((skill_dir / "adaptation.json").read_text(encoding="utf-8"))
        assert adaptation["root_module"] == module_name
        assert "source_compile" in adaptation["revalidation_required"]


def test_clean_removes_previous_skill_directories(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "rtl" / "one.v", "module one(input wire clk); endmodule\n")
    output = tmp_path / "skills"
    stale = output / "stale_skill"
    stale.mkdir(parents=True)
    (stale / "old.txt").write_text("old", encoding="utf-8")

    build_skill_library(repo, output, clean=True, llm=FakeClassifierLLM())
    assert not stale.exists()
    assert (output / "one" / "module_info.json").exists()


def test_llm_classification_cache_is_reused(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "rtl" / "one.v", "module one(input wire clk); endmodule\n")
    output = tmp_path / "skills"
    llm = FakeClassifierLLM()
    build_skill_library(repo, output, clean=True, llm=llm)
    assert llm.calls == 2

    second_llm = FakeClassifierLLM()
    build_skill_library(repo, output, clean=False, llm=second_llm)
    assert second_llm.calls == 0
    assert (output / ".llm_cache").exists()

    third_llm = FakeClassifierLLM()
    build_skill_library(repo, output, clean=True, llm=third_llm)
    assert third_llm.calls == 0
    assert (output / ".llm_cache").exists()
