from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import shutil
import subprocess
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REF_DIR = ROOT / "data" / "refs"
GEN_DIR = ROOT / "work" / "generated"
REPORT_DIR = ROOT / "work" / "reports"
REPORT_PATH = REPORT_DIR / "report.md"


@dataclasses.dataclass
class RetrievalHit:
    path: Path
    score: int
    matched: list[str]
    snippet: str


@dataclasses.dataclass
class Attempt:
    index: int
    rtl_path: Path
    tb_path: Path
    ok: bool
    command_log: str
    repair_note: str = ""


def log(step: str, message: str) -> None:
    now = dt.datetime.now().strftime("%H:%M:%S")
    print(f"[{now}] [{step}] {message}", flush=True)


def ensure_dirs() -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)


def spec_keywords(spec: str) -> list[str]:
    raw = spec.lower().replace("-", " ").replace("_", " ").split()
    stopwords = {
        "a",
        "an",
        "and",
        "the",
        "to",
        "with",
        "use",
        "one",
        "first",
        "input",
        "output",
        "outputs",
        "create",
    }
    aliases = {
        "uart": ["uart", "serial", "baud", "transmitter", "tx"],
        "transmitter": ["transmitter", "tx", "send"],
        "start": ["start"],
        "data": ["data"],
        "busy": ["busy"],
        "done": ["done"],
        "stop": ["stop"],
    }
    keywords: list[str] = []
    for token in raw:
        token = "".join(ch for ch in token if ch.isalnum())
        if not token or token in stopwords:
            continue
        keywords.append(token)
        keywords.extend(aliases.get(token, []))
    if "uart" not in keywords:
        keywords.extend(["uart", "transmitter", "tx"])
    return sorted(set(keywords))


def retrieve_refs(spec: str, limit: int = 3) -> list[RetrievalHit]:
    keywords = spec_keywords(spec)
    hits: list[RetrievalHit] = []
    for path in REF_DIR.rglob("*.v"):
        text = path.read_text(encoding="utf-8")
        lowered = text.lower()
        matched = [kw for kw in keywords if kw in lowered or kw in path.name.lower()]
        if matched:
            hits.append(
                RetrievalHit(
                    path=path,
                    score=len(matched),
                    matched=matched,
                    snippet="\n".join(text.splitlines()[:18]),
                )
            )
    hits.sort(key=lambda item: (-item.score, str(item.path)))
    return hits[:limit]


def require_uart_spec(spec: str) -> None:
    lowered = spec.lower()
    if not any(token in lowered for token in ("uart", "serial", "transmitter", "tx")):
        raise ValueError("Only UART transmitter style specs are supported in this first version.")


def generate_rtl(spec: str, refs: list[RetrievalHit], inject_bug: bool = False) -> str:
    require_uart_spec(spec)
    data_index_decl = "reg [1:0] bit_index;" if inject_bug else "reg [2:0] bit_index;"
    return f"""\
`timescale 1ns/1ps

// Generated by mini-rtl-agent.
// Spec: {spec}
// Retrieved refs: {", ".join(hit.path.name for hit in refs) or "none"}
module uart_tx #(
    parameter CLKS_PER_BIT = 16
) (
    input wire clk,
    input wire rst,
    input wire start,
    input wire [7:0] data,
    output reg tx,
    output reg busy,
    output reg done
);
    localparam S_IDLE  = 3'd0;
    localparam S_START = 3'd1;
    localparam S_DATA  = 3'd2;
    localparam S_STOP  = 3'd3;

    reg [2:0] state;
    reg [15:0] clk_count;
    {data_index_decl}
    reg [7:0] data_latch;

    always @(posedge clk) begin
        if (rst) begin
            state <= S_IDLE;
            clk_count <= 16'd0;
            bit_index <= 0;
            data_latch <= 8'd0;
            tx <= 1'b1;
            busy <= 1'b0;
            done <= 1'b0;
        end else begin
            done <= 1'b0;
            case (state)
                S_IDLE: begin
                    tx <= 1'b1;
                    busy <= 1'b0;
                    clk_count <= 16'd0;
                    bit_index <= 0;
                    if (start) begin
                        data_latch <= data;
                        busy <= 1'b1;
                        state <= S_START;
                    end
                end
                S_START: begin
                    tx <= 1'b0;
                    if (clk_count == CLKS_PER_BIT - 1) begin
                        clk_count <= 16'd0;
                        state <= S_DATA;
                    end else begin
                        clk_count <= clk_count + 16'd1;
                    end
                end
                S_DATA: begin
                    tx <= data_latch[bit_index];
                    if (clk_count == CLKS_PER_BIT - 1) begin
                        clk_count <= 16'd0;
                        if (bit_index == 3'd7) begin
                            bit_index <= 0;
                            state <= S_STOP;
                        end else begin
                            bit_index <= bit_index + 1'b1;
                        end
                    end else begin
                        clk_count <= clk_count + 16'd1;
                    end
                end
                S_STOP: begin
                    tx <= 1'b1;
                    if (clk_count == CLKS_PER_BIT - 1) begin
                        clk_count <= 16'd0;
                        busy <= 1'b0;
                        done <= 1'b1;
                        state <= S_IDLE;
                    end else begin
                        clk_count <= clk_count + 16'd1;
                    end
                end
                default: begin
                    state <= S_IDLE;
                end
            endcase
        end
    end
endmodule
"""


def generate_testbench() -> str:
    return """\
`timescale 1ns/1ps

module tb_uart_tx;
    localparam CLKS_PER_BIT = 8;

    reg clk = 1'b0;
    reg rst = 1'b1;
    reg start = 1'b0;
    reg [7:0] data = 8'h00;
    wire tx;
    wire busy;
    wire done;

    integer i;
    integer errors = 0;
    reg [7:0] expected = 8'hA5;

    uart_tx #(.CLKS_PER_BIT(CLKS_PER_BIT)) dut (
        .clk(clk),
        .rst(rst),
        .start(start),
        .data(data),
        .tx(tx),
        .busy(busy),
        .done(done)
    );

    always #5 clk = ~clk;

    task expect_tx;
        input expected_bit;
        input [127:0] label;
        begin
            if (tx !== expected_bit) begin
                $display("FAIL %0s: expected tx=%0b got %0b at %0t", label, expected_bit, tx, $time);
                errors = errors + 1;
            end
        end
    endtask

    initial begin
        repeat (4) @(posedge clk);
        rst <= 1'b0;
        repeat (2) @(posedge clk);

        data <= expected;
        start <= 1'b1;
        @(posedge clk);
        start <= 1'b0;

        @(negedge tx);
        repeat (CLKS_PER_BIT / 2) @(posedge clk);
        expect_tx(1'b0, "start bit");

        for (i = 0; i < 8; i = i + 1) begin
            repeat (CLKS_PER_BIT) @(posedge clk);
            expect_tx(expected[i], "data bit");
        end

        repeat (CLKS_PER_BIT) @(posedge clk);
        expect_tx(1'b1, "stop bit");

        wait(done === 1'b1);
        @(posedge clk);
        if (busy !== 1'b0) begin
            $display("FAIL busy: expected busy=0 after done got %0b", busy);
            errors = errors + 1;
        end

        if (errors == 0) begin
            $display("PASS uart_tx");
            $finish;
        end

        $display("FAIL uart_tx errors=%0d", errors);
        $fatal(1);
    end

    initial begin
        #5000;
        $display("FAIL timeout");
        $fatal(1);
    end
endmodule
"""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    log("write", str(path.relative_to(ROOT)))


def run_command(command: list[str]) -> tuple[bool, str]:
    log("run", " ".join(command))
    completed = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    output = completed.stdout.strip()
    if output:
        for line in output.splitlines():
            log("tool", line)
    return completed.returncode == 0, output


def simulate(rtl_path: Path, tb_path: Path, attempt: int) -> tuple[bool, str]:
    if shutil.which("iverilog") is None:
        raise RuntimeError("Missing required simulator: iverilog")
    if shutil.which("vvp") is None:
        raise RuntimeError("Missing required simulator: vvp")

    sim_bin = GEN_DIR / f"sim_attempt_{attempt}.vvp"
    ok_compile, compile_log = run_command(
        ["iverilog", "-g2012", "-Wall", "-o", str(sim_bin), str(tb_path), str(rtl_path)]
    )
    if not ok_compile:
        return False, compile_log

    ok_run, run_log = run_command(["vvp", str(sim_bin)])
    combined = "\n".join(part for part in (compile_log, run_log) if part)
    return ok_run, combined


def repair_rtl(previous_rtl: str, sim_log: str) -> tuple[str, str]:
    note = "No known repair matched; regenerating clean UART TX template."
    repaired = generate_rtl(
        "UART transmitter, 8 data bits LSB first, start/busy/done",
        refs=[],
        inject_bug=False,
    )
    if "timeout" in sim_log.lower() or "data bit" in sim_log.lower():
        note = "Simulation pointed at frame/data progress; widened bit_index to cover all 8 bits."
        repaired = previous_rtl.replace("reg [1:0] bit_index;", "reg [2:0] bit_index;")
    return repaired, note


def build_report(spec: str, refs: list[RetrievalHit], attempts: list[Attempt]) -> str:
    status = "PASS" if attempts and attempts[-1].ok else "FAIL"
    ref_lines = "\n".join(
        f"- `{hit.path.relative_to(ROOT)}` score={hit.score} matched={', '.join(hit.matched)}"
        for hit in refs
    ) or "- No references found."
    attempt_lines = []
    for attempt in attempts:
        result = "PASS" if attempt.ok else "FAIL"
        log_block = attempt.command_log or "(no simulator output)"
        repair = f"\nRepair note: {attempt.repair_note}" if attempt.repair_note else ""
        attempt_lines.append(
            f"### Attempt {attempt.index}: {result}\n"
            f"- RTL: `{attempt.rtl_path.relative_to(ROOT)}`\n"
            f"- Testbench: `{attempt.tb_path.relative_to(ROOT)}`{repair}\n\n"
            f"```text\n{log_block}\n```"
        )

    return f"""\
# mini-rtl-agent Report

Generated: {dt.datetime.now().isoformat(timespec="seconds")}

## Status

{status}

## Input Spec

```text
{spec}
```

## Retrieved References

{ref_lines}

## Attempts

{chr(10).join(attempt_lines)}

## Final Artifacts

- RTL: `work/generated/uart_tx.v`
- Testbench: `work/generated/tb_uart_tx.v`
- Report: `work/reports/report.md`
"""


def run_agent(spec: str, max_repairs: int, inject_bug: bool) -> int:
    ensure_dirs()
    log("spec", spec)

    refs = retrieve_refs(spec)
    if not refs:
        log("retrieve", "no matching references found")
    for hit in refs:
        log(
            "retrieve",
            f"{hit.path.relative_to(ROOT)} score={hit.score} matched={','.join(hit.matched)}",
        )

    tb_text = generate_testbench()
    tb_path = GEN_DIR / "tb_uart_tx.v"
    write_text(tb_path, tb_text)

    rtl_text = generate_rtl(spec, refs, inject_bug=inject_bug)
    rtl_path = GEN_DIR / "uart_tx.v"
    attempts: list[Attempt] = []

    max_attempts = max_repairs + 1
    repair_note = ""
    for index in range(1, max_attempts + 1):
        log("attempt", f"{index}/{max_attempts}")
        write_text(rtl_path, rtl_text)
        ok, command_log = simulate(rtl_path, tb_path, index)
        attempts.append(
            Attempt(
                index=index,
                rtl_path=rtl_path,
                tb_path=tb_path,
                ok=ok,
                command_log=command_log,
                repair_note=repair_note,
            )
        )
        if ok:
            log("result", "simulation passed")
            break
        if index == max_attempts:
            log("result", "repair budget exhausted")
            break
        rtl_text, repair_note = repair_rtl(rtl_text, command_log)
        log("repair", repair_note)

    report = build_report(spec, refs, attempts)
    write_text(REPORT_PATH, report)
    return 0 if attempts and attempts[-1].ok else 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a minimal RTL agent demo.")
    parser.add_argument(
        "--spec",
        default=(
            "Create a UART transmitter with clk, rst, start, 8-bit data input, "
            "tx, busy, and done outputs. Use one start bit, 8 data bits LSB first, "
            "and one stop bit."
        ),
        help="Natural language RTL spec.",
    )
    parser.add_argument("--max-repairs", type=int, default=3, help="Maximum repair iterations.")
    parser.add_argument(
        "--inject-bug",
        action="store_true",
        help="Generate a known first-attempt bug to exercise the repair loop.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.max_repairs < 0 or args.max_repairs > 3:
        raise SystemExit("--max-repairs must be between 0 and 3")
    try:
        return run_agent(args.spec, args.max_repairs, args.inject_bug)
    except Exception as exc:
        log("error", str(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
